blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ æ–°åŠŸèƒ½è¯·æ±‚
    url: https://github.com/IPTV-CN/IPTV/discussions/new
    about: ä»»ä½•æ–°çš„æƒ³æ³•æˆ–æ–°çš„åŠŸèƒ½è¦æ±‚
  - name: â“ é—®ä¸€ä¸ªé—®é¢˜
    url: https://github.com/IPTV-CN/IPTV/discussions/new
    about: è¯¢é—®æœ‰å…³æ­¤é¡¹ç›®çš„é—®é¢˜
